NEID_SOLAR_SCRIPTS: NeidSolarScripts.jl
NEID_NIGHT_SCRIPTS: NeidNightScripts
NEID_SSOF_SCRIPTS: SSOFApplication
CUTOFF_TIME_OF_DAY_START: '22:30:00'
CUTOFF_TIME_OF_DAY_END: '16:45:00'
DOWNLOAD_SCRIPT: shared/download_codes/download_neid_data.py  # path relative to pipeline_dir
NEXSCI_ID: nexsci_id.toml  # path relative to analysis run directory
INSTRUMENT: neid_night
#INCLUDE_STARS_IN_DATA_FOLDER: True
INCLUDE_STARS_IN_DATA_FOLDER: False
STANDARD_STARS:
  #- HD 4628
  - HD 9407
  #- HD 10700
  #- HD 89269
  #- HD 127334
  #- GJ 699
  #- HD 185144
  #- HD 221354
PROGRAMS:
  #- 2021A-2015
  #- 2021B-2015
  #- 2021A-0390
  #- 2021B-0450
RUN_ALL_DATES: no  # Whether to run all dates b/w given START_DATE and END_DATE
INPUT_VERSION: 1.1
MANIFEST_VERSION: 1.1
USER_ID: # Optional. If no USER_ID is provided here, the environment variable USER will be used
PIPELINE_ID: test
params:
  max_spectra_number: 20
  last_order: 118
  orders: 25-75 # default:25-75. Single number needs to be enclosed by quotes '', so it will be taken as string instead of number. TODO: extend gather_ssof's ability to accept intermittent range, e.g. "67-70, 77".
  ssof_flags: 
    orig: 
    #someflag: --someflag false
