NEID_SOLAR_SCRIPTS: NeidSolarScripts.jl
EXCLUDE_FILENAME:  days_to_exclude.csv  # path relative to data
DOWNLOAD_SCRIPT: shared/download_codes/download_neid_data.py  # path relative to pipeline_dir
NEXSCI_ID: nexsci_id.toml  # path relative to analysis run directory
COOKIE: cookie  # path relative to analysis run directory
INSTRUMENT: neid_night
STANDARD_STARS:
  - HD 4628
  - HD 9407
  - HD 10700
  - HD 89269
  - HD 127334
  - GJ 699
  - HD 185144
  - HD 221354
PROGRAMS:
  - 2021A-2015
  - 2021B-2015
  - 2021A-0390
  - 2021B-0450
INPUT_VERSION: 1.1
PYRHELIOMETER_VERSION: 1.1
MANIFEST_VERSION: 1.1
CCFS_VERSION: 1.1
RVS_VERSION: 1.2
REPORT_DAILY_VERSION: 1.2
REPORT_MONTHLY_VERSION: 1.0
REPORT_ALL_VERSION: 1.0
COMBINE_RVS_VERSION: 1.0
USER_ID: # Optional. If no USER_ID is provided here, the environment variable USER will be used
PIPELINE_ID: test2
params: # most filepaths in this section are relative to NEID_SOLAR_SCRIPTS  # TODO: Make relative to analysis run directory
  prep_ccf_date_path: 2021/05/27
  #anchors: scripts/data/anchors_20210527.jld2
  linelist: 
    orig: scripts/data/linelist_20210208.csv
    #overlap=1: data/VALD_species=all_depthcutoff=0.05_overlapcutoff=1e-05_allowBlends=0_badLineFilter=ESPRESSOG2_rejectTelluricSlope=0.0_waves=Reiners_depths=original_nbin=1_binparam=depth_n=0.csv
    #overlap=3: data/VALD_species=all_depthcutoff=0.05_overlapcutoff=3e-05_allowBlends=0_badLineFilter=ESPRESSOG2_rejectTelluricSlope=0.0_waves=Reiners_depths=original_nbin=1_binparam=depth_n=0.csv
    #overlap=6: data/VALD_species=all_depthcutoff=0.05_overlapcutoff=6e-05_allowBlends=0_badLineFilter=ESPRESSOG2_rejectTelluricSlope=0.0_waves=Reiners_depths=original_nbin=1_binparam=depth_n=0.csv
  #ccf_template: scripts/data/template.jld2
  #ccf_template: daily_ccfs_orig_norm=blaze-mask=1.jld2
  ccf_template_date: 2021/05/27
  orders_first: 56
  orders_last: 108
  range_no_mask_change: 6.0
  calc_order_ccfs_flags: #--ccf_mid_vel 640 --variable_mask_scale --recompute_line_weights
    norm=blaze&mask=1: --ccf_mid_vel -640 --mask_scale_factor 1
    #norm=blaze&mask=3: --ccf_mid_vel -640 --mask_scale_factor 3
    #norm=blaze&mask=5: --ccf_mid_vel -640 --mask_scale_factor 5
    #norm=blaze&mask=var: --ccf_mid_vel -640 --variable_mask_scale
    #norm=cont&mask=1: --ccf_mid_vel -640 --apply_continuum_normalization --mask_scale_factor 1
    #norm=cont&mask=3: --ccf_mid_vel -640 --apply_continuum_normalization --mask_scale_factor 3
    #norm=cont&mask=5: --ccf_mid_vel -640 --apply_continuum_normalization --mask_scale_factor 5
    #norm=cont&mask=var: --ccf_mid_vel -640 --apply_continuum_normalization --variable_mask_scale
  daily_rvs_flags: --rv_alg gaussian_template_quadratic
