#DATA_ROOT: /gpfs/group/ebf11/default/RISE_NEID/data
DATA_ROOT: /gpfs/group/ebf11/default/pipeline/data 
DATA_L0_ROOT: /gpfs/scratch/ebf11/data_tmp
NEXSCI_ID: /gpfs/group/ebf11/default/pipeline/NeidSolarScripts.jl/nexsci_id.toml
INSTRUMENT: neid_solar
INPUT_VERSION: 1.1
PYRHELIOMETER_VERSION: 1.1
MANIFEST_VERSION: 1.1
CCFS_VERSION: 1.1
RVS_VERSION: 1.2
REPORT_DAILY_VERSION: 1.2
REPORT_MONTHLY_VERSION: 1.0
REPORT_ALL_VERSION: 1.0
COMBINE_RVS_VERSION: 1.0
LEVEL: 2
#USER_ID: dus73
USER_ID: ebf11
PIPELINE_ID: test1
#NEID_SOLAR_SCRIPTS: /gpfs/group/ebf11/default/ebf11/neid_solar/code/NeidSolarScripts.jl
NEID_SOLAR_SCRIPTS: /gpfs/group/ebf11/default/pipeline/NeidSolarScripts.jl
#PYROHELIO_DIR: /gpfs/group/ebf11/default/ebf11/neid_solar/data/pyrohelio/202110_fromChad/
PYRHELIO_DIR: /gpfs/group/ebf11/default/pipeline/data/neid_solar/pyrheliometer
EXCLUDE_FILENAME:  /gpfs/group/ebf11/default/pipeline/shared/days_to_exclude.csv 
params:
  anchors: /gpfs/group/ebf11/default/pipeline/NeidSolarScripts.jl/scripts/anchors_20210527.jld2
  #linelist:  /gpfs/group/ebf11/default/pipeline/NeidSolarScripts.jl/scripts/linelist_20210208.csv
  linelist:  /gpfs/group/ebf11/default/pipeline/NeidSolarScripts.jl/scripts/linelist_20210527.csv
  ccf_template: /gpfs/group/ebf11/default/pipeline/NeidSolarScripts.jl/scripts/template.jld2
  orders_first: 56
  #orders_last: 105
  orders_last: 108
  range_no_mask_change: 6.0
  calc_order_ccfs_flags: --ccf_mid_vel 640 --variable_mask_scale --recompute_line_weights
  daily_rvs_flags: --rv_alg gaussian_template_quadratic
