NEID_SOLAR_SCRIPTS: NeidSolarScripts.jl
EXCLUDE_FILENAME:  data/days_to_exclude.csv 
INSTRUMENT: neid_solar
INPUT_VERSION: 1.1
PYRHELIOMETER_VERSION: 1.1
MANIFEST_VERSION: 1.1
CCFS_VERSION: 1.1
RVS_VERSION: 1.2
REPORT_DAILY_VERSION: 1.2
REPORT_MONTHLY_VERSION: 1.0
REPORT_ALL_VERSION: 1.0
COMBINE_RVS_VERSION: 1.0
USER_ID: dus73
PIPELINE_ID: test1
params: # filepaths in this section are relative to NEID_SOLAR_SCRIPTS
  NEXSCI_ID: nexsci_id.toml
  anchors: scripts/anchors_20210527.jld2
  linelist: 
    orig: scripts/linelist_20210208.csv
    overlap=1: data/VALD_species=all_depthcutoff=0.05_overlapcutoff=1e-05_allowBlends=0_badLineFilter=ESPRESSOG2_rejectTelluricSlope=0.0_waves=Reiners_depths=original_nbin=1_binparam=depth_n=0.csv
    overlap=3: data/VALD_species=all_depthcutoff=0.05_overlapcutoff=3e-05_allowBlends=0_badLineFilter=ESPRESSOG2_rejectTelluricSlope=0.0_waves=Reiners_depths=original_nbin=1_binparam=depth_n=0.csv
    overlap=6: data/VALD_species=all_depthcutoff=0.05_overlapcutoff=6e-05_allowBlends=0_badLineFilter=ESPRESSOG2_rejectTelluricSlope=0.0_waves=Reiners_depths=original_nbin=1_binparam=depth_n=0.csv
  ccf_template: scripts/template.jld2
  orders_first: 56
  orders_last: 108
  range_no_mask_change: 6.0
  calc_order_ccfs_flags: #--ccf_mid_vel 640 --variable_mask_scale --recompute_line_weights
    norm=blaze-mask=1: --ccf_mid_vel -640 --mask_scale_factor 1
    norm=blaze-mask=3: --ccf_mid_vel -640 --mask_scale_factor 3
    norm=blaze-mask=5: --ccf_mid_vel -640 --mask_scale_factor 5
    norm=blaze-mask=var: --ccf_mid_vel -640 --variable_mask_scale
    norm=cont-mask=1: --ccf_mid_vel -640 --apply_continuum_normalization --mask_scale_factor 1
    norm=cont-mask=3: --ccf_mid_vel -640 --apply_continuum_normalization --mask_scale_factor 3
    norm=cont-mask=5: --ccf_mid_vel -640 --apply_continuum_normalization --mask_scale_factor 5
    norm=cont-mask=var: --ccf_mid_vel -640 --apply_continuum_normalization --variable_mask_scale
  daily_rvs_flags: --rv_alg gaussian_template_quadratic
