default-resources: mem_mb_per_cpu=4000
cluster: "sbatch --job-name={rule} -A open -p open -t 4:00:00 -N 1 -n 1 --mem-per-cpu={resources.mem_mb_per_cpu} --export=ALL"
jobs: 90
verbose: true
notemp: true
