__default__:
  jobname: "{rule}"
  nodes: 1
  ppn: 1
  #pmem: "8000mb"
  pmem: "16000mb"
  walltime: "24:00:00"
  account: "open"
  email: "ebf11@psu.edu"
  mailon: "n"
  jobout: "oe"
  outdir: "logs/"
